### ISSUE TITLE
required_signatures is not used any more

### ISSUE THREAD

**Issue by akolotov** [poanetwork/deployment-bridge#30]
As per latest updates in `poa-bridge` repo (https://github.com/poanetwork/poa-bridge/commit/7c429798b391fb1d8849cf15245875126938fe92), the configuration parameter `authorities.required_signatures` is not used any more. So, it is not needed to be configured as part of bridge instance deployment process.

**Comment by phahulin** [comment]
Since that version is not released yet, I've created a separate branch https://github.com/poanetwork/deployment-bridge/commit/67b9bb36711282df1d0b61704736dccd49288243 so that master still stores the latest stable playbook.

If we ever release that version of rust code or abandon it completely, I'll merge it into master.

Let me know if you think this is OK and this issue can be closed

**Comment by akolotov** [comment]
Ok. Let's do this in the way you suggested
